version: "3.8"

services:
  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_DB: devops
    networks:
      - flask-app

    depends_on:
      - mysql

    restart: always

    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: "devops"
    volumes:
      - flask-app:/var/lib/mysql
    networks:
      - flask-app
    restart: always

    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h" , "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


volumes:
  flask-app:

networks:
  flask-app: