pipeline {
    agent any

    stages {
        stage('hello'){
            steps {
                echo 'Hello My Two tier application is now worked.....'
            }
        }
        stage('Clone Website') {
            steps {
                git url: 'https://github.com/DEVKUMARSAINI545/two-tier-application-deploy.git', branch: "main"
            }
        }
        
        
          stage('Terraform Apply') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'awsCredId'
                ]]) {
                    dir('terraform') {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
    }
}
